### ISSUE TITLE
Domoticz API breaking changes

### ISSUE THREAD

**Issue by user8446** [Paul-VW/script.domoticz.scenes#8]
Hi just letting you know that there are upcoming API breaking changes. Please see: https://github.com/domoticz/domoticz-android/issues/692

**Comment by Paul-VW** [comment]
New (beta) release of Domoticz Scenes is now available. This should work fine with Domoticz 2023.1 and below as well as with 2023.2 and above.
Also some other fixes are applied. Still needs to be published to the Kodi repo for automatic updates, so for now manual update available.

**Comment by user8446** [comment]
Thank you!
